---
- hosts: media_servers
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Node.js and npm
      apt:
        name:
          - nodejs
          - npm
        state: present

    - name: Install FFmpeg
      apt:
        name: ffmpeg
        state: present

    - name: Clone the repository
      git:
        repo: 'https://github.com/yourusername/media-processing-server.git'
        dest: /opt/media-processing-server
        version: main

    - name: Install Node.js dependencies
      npm:
        path: /opt/media-processing-server

    - name: Start stream conversion server
      shell: nohup node media_server.js > stream_server.log 2>&1 &
      args:
        chdir: /opt/media-processing-server

    - name: Start file conversion server
      shell: nohup node media_converter_server.js > file_server.log 2>&1 &
      args:
        chdir: /opt/media-processing-server
